version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - '5402:5432'
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recollector
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev_pass

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
