import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the state interface for the drawer toggle functionality
export interface DrawerToggledState {
    value: boolean;
}

// Initial state for the drawer toggle, starting as 'false' (closed)
const initialState: DrawerToggledState = {
    value: false
};

// Create a slice for the drawer toggle functionality
export const drawerSlice = createSlice(
    {
        name: "drawerToggled",
        initialState,
        reducers: {
            /**
             * Action to switch the drawer on (open).
             * This sets the drawer state to `true`.
             *
             * @param {DrawerToggledState} state - The current state of the drawer.
             */
            drawerSwitchOn: (state: DrawerToggledState) => {
                state.value = true;
            },

            /**
             * Action to switch the drawer off (close).
             * This sets the drawer state to `false`.
             *
             * @param {DrawerToggledState} state - The current state of the drawer.
             */
            drawerSwitchOff: (state: DrawerToggledState) => {
                state.value = false;
            },

            /**
             * Action to set the drawer state to a custom value.
             *
             * @param {DrawerToggledState} state - The current state of the drawer.
             * @param {PayloadAction<boolean>} action - The action containing the new state.
             */
            drawerSetCustomState: (state: DrawerToggledState, action: PayloadAction<boolean>) => {
                state.value = action.payload;
            }
        }
    }
);

// Export the actions generated by createSlice
export const { drawerSwitchOn, drawerSwitchOff, drawerSetCustomState } = drawerSlice.actions;

// Export the reducer to be used in the store
export default drawerSlice.reducer;
