-- Create user_settings table
CREATE TABLE "recollector"."user_settings" (
    "setting_id"                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"                   bigint      NOT NULL REFERENCES "recollector"."users" ("user_id") ON DELETE CASCADE,

    -- Settings for categories
    "category_background_color" VARCHAR(50) NOT NULL,
    "category_item_color"       VARCHAR(50) NOT NULL,
    "category_fab_color"        VARCHAR(50) NOT NULL,
    "category_page_size"        INTEGER     NOT NULL,

    -- Settings for items
    "item_background_color"     VARCHAR(50) NOT NULL,
    "item_item_color"           VARCHAR(50) NOT NULL,
    "item_fab_color"            VARCHAR(50) NOT NULL,
    "item_page_size"            INTEGER     NOT NULL,

    "created_at"                timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"                timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
                                           );
