-- Create the invalidated_tokens table
CREATE TABLE "recollector"."invalidated_tokens" (
    "token_id"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"        bigint        NOT NULL REFERENCES "recollector"."users" ("user_id") ON DELETE CASCADE,
    "token"          VARCHAR(1024) NOT NULL,                               -- Store JWT token as a string (may need to adjust length)
    "invalidated_at" timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,     -- Timestamp of when token was invalidated
    "expires_at"     timestamptz   NOT NULL,                               -- Timestamp when the token is set to expire

    CONSTRAINT "unique_invalid_token_per_user" UNIQUE ("user_id", "token") -- Ensure unique tokens per user
                                                );

-- Create an index on the expires_at column for efficient deletion
CREATE INDEX "idx_invalidated_tokens_expires_at" ON "recollector"."invalidated_tokens" ("expires_at");