import {createSlice, PayloadAction} from "@reduxjs/toolkit";
import {logger} from "../../../config/appConfig";

const log = logger.getLogger("categorySlice");

export interface GlobalState {
    currentCategoryId?: number;
    currentCategoryName?: string;
    userIsLoggedIn?: boolean;
    userEmail?: string;
    userTimeExp?: number;
    userDateTimeExp?: Date;
}

const initialState: GlobalState = {
    currentCategoryId: -1,
    currentCategoryName: "",
    userIsLoggedIn: false,
    userEmail: "",
    userTimeExp: 0
};

export const globalSlice = createSlice({
    name: "globals",
    initialState,
    reducers: {
        setUserEmail: (state: GlobalState, action: PayloadAction<string>) => {
            log.debug(`globalSlice.reducers.setUserEmail. current state: ${JSON.stringify(state)}, action: ${JSON.stringify(action.payload)}`);
            state.userEmail = action.payload;
        },
        setUserIsLoggedIn: (state: GlobalState, action: PayloadAction<boolean>) => {
            log.debug(`globalSlice.reducers.setUserIsLoggedIn. current state: ${JSON.stringify(state)}, action: ${JSON.stringify(action.payload)}`);
            state.userIsLoggedIn = action.payload;
        },
        setUserTimeExp: (state: GlobalState, action: PayloadAction<number>) => {
            log.debug(`globalSlice.reducers.setUserTimeExp. current state: ${JSON.stringify(state)}, action: ${JSON.stringify(action.payload)}`);
            let dateTimeSeconds = action.payload;
            const expDate = new Date(dateTimeSeconds * 1000);
            state.userTimeExp = action.payload;
            state.userDateTimeExp = expDate;
        },
        setCurrentCategoryId: (state: GlobalState, action: PayloadAction<number>) => {
            log.debug(`globalSlice.reducers.setCurrentCategoryId. current state: ${JSON.stringify(state)}, action: ${JSON.stringify(action.payload)}`);
            state.currentCategoryId = action.payload;
        },
        setCurrentCategoryName: (state: GlobalState, action: PayloadAction<string>) => {
            log.debug(`globalSlice.reducers.setCurrentCategoryName. current state: ${JSON.stringify(state)}, action: ${JSON.stringify(action.payload)}`);
            state.currentCategoryName = action.payload;
        }
    }
});

// Export the actions generated by createSlice
export const {
    setUserEmail,
    setUserIsLoggedIn,
    setUserTimeExp,
    setCurrentCategoryId,
    setCurrentCategoryName
} = globalSlice.actions;

// Export the reducer to be used in the store
export default globalSlice.reducer;
